name: Docker Image (UI + GHCR Multi-Arch)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref to build (branch/tag/sha)'
        required: false
        default: 'main'
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (build exactly this commit)
        uses: actions/checkout@v4
        with:
          # ✅ 用当前触发的提交，而不是 main 默认分支
          ref: ${{ github.sha }}
          submodules: recursive
          fetch-depth: 0

      - name: Normalize repo to lowercase
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # ✅ 构建前强校验：Dockerfile 里不能再出现 --frozen-lockfile
      - name: Sanity check Dockerfile (no --frozen-lockfile)
        run: |
          echo '--- yarn install lines ---'
          nl -ba Dockerfile | sed -n '/yarn .*install/p'
          if grep -q -- "--frozen-lockfile" Dockerfile; then
            echo "::error::Dockerfile still contains --frozen-lockfile. You're building the wrong file/branch."
            exit 1
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_LC }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # ✅ 换新缓存key并且本次完全不走缓存，避免吃到旧层里的坏命令
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_LC }}/buildcache-v3
          cache-to:   type=registry,ref=ghcr.io/${{ env.REPO_LC }}/buildcache-v3,mode=max
          no-cache: true
          build-args: |
            GO_VERSION=1.23
            NODE_VERSION=20
