name: Docker Image (UI + GHCR Multi-Arch)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref to build (branch/tag/sha)'
        required: false
        default: 'main'
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # 关键：允许推送到 GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
          submodules: recursive

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}   # 只推 GHCR
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录 GHCR（用 GITHUB_TOKEN 即可）
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64 + arm64, UI embedded)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile           # 你的“带前端嵌入”的 Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=1.22
            NODE_VERSION=20
